[project]
name = "comiket"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fsspec>=2025.9.0",
    "pycdlib>=1.14.0",
]
